# -*- coding: utf-8 -*-
"""01_generacion_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NN7SQ5hwl5OOoHF1xFAWZzfN5BuXb4vk
"""

# Librerías
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
import os

# Definimos la ruta donde se guardarán los archivos
ruta = "/content/drive/MyDrive/Ventas_EstudIA/data_ventas/"

# Si la carpeta NO existe, la crea
if not os.path.exists(ruta):
    os.makedirs(ruta)

!ls "/content/drive/MyDrive/Ventas_EstudIA/data_ventas/"

#FUNCIÓN CLAVE → AUTOINCREMENTAL

def ultimo_id(nombre_archivo, columna_id):
  try:
    #Leer el archivo existente
    df = pd.read_csv(ruta + nombre_archivo)

    #Busca el ultimo valor del id y le suma 1
    return df[columna_id].max() + 1
  except:
    # Si el archivo no existe, comienza en 1
    return 1

# CSV de dimesión de clientes

#Cantidad de clientes
num_clientes = 100

clientes = pd.DataFrame({
    # ID autoincrementa
    'id_cliente': range(1, num_clientes + 1),

    # Creamos el nombre ficticio Cliente_1
    "nombre": [f"Cliente_{i}" for i in range(1, num_clientes + 1)],

    #Ciudad aletatoria
    "ciudad": np.random.choice(["bogota", "medellin", "cali", "barranquilla", "cartagena", "cucuta"], num_clientes),

    #Tipo de cliente
    "segmento": np.random.choice(["nuevo", "frecuente", "vip"], num_clientes)
})
#Guardar como CSV
clientes.to_csv(ruta + "dim_clientes.csv", index=False)

# CSV de dimesión de productos

#Cantidad de productos
num_productos = 50

productos = pd.DataFrame({
    # id_producto
    "id_producto": range(1, num_productos + 1),

    # Nombre ficticio
    "nombre_producto": [f"Producto_{i}" for i in range(1, num_productos + 1)],

    # Categoria aleatoria
    "categoria": np.random.choice(["abarrotes", "lacteos", "aseo", "bebidas", "frutas_verduras","snacks"], num_productos),

    #Marcas ficticias
    "marca": np.random.choice(["alpina", "colanta", "postobon", "zenu","nescafe", "diana", "doria"], num_productos)
})
#Guardar como CSV
productos.to_csv(ruta + "dim_productos.csv", index=False)

# CSV de dimesión de tiendas

# Lista de ciudades (las mismas de clientes)
ciudades = ["bogota", "medellin", "cali", "barranquilla", "cartagena", "cucuta"]


tiendas = pd.DataFrame({
    # ID autoincremental según cantidad de ciudades
    "id_tienda": range(1, len(ciudades) + 2),

    # Nombre de tiendas físicas + onlin
    "nombre_tienda": [f"tienda_{c}" for c in ciudades] + ["tienda_online"],

    # Ciudad
    "ciudad": ciudades + ["online"],

    # Tipos: físicas para ciudades + una online
    "tipo_tienda": ["fisica"] * len(ciudades) + ["online"]
})
#Guardar como CSV
tiendas.to_csv(ruta + "dim_tiendas.csv", index= False)

# CSV de dimesión de vendedores
vendedores = pd.DataFrame({
    # ID autoincremental
    "id_vendedor": range(1,11),
    "nombre": [f"Vendedor_{i}" for i in range(1,11)],
    "zona": np.random.choice(["norte", "sur", "este", "oeste"], 10)
})
#Guardar como CSV
vendedores.to_csv(ruta + "dim_vendedores.csv", index= False)

# FACT_VENTAS
# Número de registros nuevos
nuevos_registros = 1000

# Obtener último ID existente
inicio_id = ultimo_id("fact_ventas.csv", "event_id")

# Leer dimensiones para usar tamaños dinámicos
num_clientes = len(pd.read_csv(ruta + "dim_clientes.csv"))
num_productos = len(pd.read_csv(ruta + "dim_productos.csv"))
num_tiendas = len(pd.read_csv(ruta + "dim_tiendas.csv"))
num_vendedores = len(pd.read_csv(ruta + "dim_vendedores.csv"))

#Creación de los DATOS

ventas = pd.DataFrame({
# IDs autoincrementales
    "event_id": range(inicio_id, inicio_id + nuevos_registros),

    # Fechas aleatorias en los últimos 30 días
    "fecha": [datetime.now() - timedelta(days=random.randint(0,30)) for _ in range(nuevos_registros)],

    # Relaciones con dimensiones
    "id_cliente": np.random.randint(1, 101, nuevos_registros),
    "id_producto": np.random.randint(1, 51, nuevos_registros),
    "id_tienda": np.random.randint(1, num_tiendas + 1, nuevos_registros),
    "id_vendedor": np.random.randint(1, 11, nuevos_registros),

    "cantidad": np.random.randint(1, 5, nuevos_registros),
    "precio_unitario": np.random.uniform(5000, 50000, nuevos_registros)
})
# Calcular total
ventas["total"] = ventas["cantidad"] * ventas["precio_unitario"]

#GUARDADO INCREMENTAL

try:
    # Leer archivo existente
    existentes = pd.read_csv(ruta + "fact_ventas.csv")

    # Unir datos antiguos + nuevos
    ventas = pd.concat([existentes, ventas])

except:
    # Si no existe, sigue normal
    pass

# Guardar archivo actualizado
ventas.to_csv(ruta + "fact_ventas.csv", index=False)

#FACT_ENVIOS
inicio_envio = ultimo_id("fact_envios.csv", "id_envio")

envios = pd.DataFrame({
    "id_envio": range(inicio_envio, inicio_envio + nuevos_registros),

    #Relación con ventas
    "id_envio": ventas["event_id"].tail(nuevos_registros),

    #Fechas aleatorias
    "fecha_envio":[datetime.now() for _ in range(nuevos_registros)],
})

# Fecha de entrega (1 a 5 días después)
envios["fecha_entrega"] = envios["fecha_envio"] + pd.to_timedelta(np.random.randint(1,5, nuevos_registros), unit='d')

# Calcular tiempo de entrega
envios["tiempo_entrega"] = (envios["fecha_entrega"] - envios["fecha_envio"]).dt.days

#Estado del envío
envios["estado_envio"] = np.random.choice(["entregado", "retrasado", "cancelado"], nuevos_registros)

# Costo del envío
envios["costo_envio"] = np.random.uniform(15000,30000, nuevos_registros)

#Guardar

try:
  envios_existentes = pd.read_csv(ruta + "fact_envios.csv")
  envios = pd.concat([envios_existentes, envios])
except:
  pass

envios.to_csv(ruta + "fact_envios.csv", index= False)